deactivating query reviewer It causes an error on post requests NoMethodError: undefined method `reverse' for nil:NilClass There is a fix but documentation seems to point to it only working for Rails 4